Версия 1.1
avalon-dev-j30/lab-2-AntonNeverovich pull request #1
Opened 2019-05-29 13:16 UTC by AntonNeverovich

Добрый день!

Сделал для MySQL на удаленном сервере. Хотел попробовать сделать удаленное подключение.

Не совсем понятно условие задачи (TODO #13):  "Метод сохраняет текущий объект в базе данных. Если запись ещё не существует, то выполняется запрос типа INSERT. Если запись уже существует в базе данных, то выполняется запрос типа UPDATE."
Текущий объект – что это? Экземпляр класса `ProductCode`? Тогда возникает вопрос: как его сравнивать с самим с собой? В текущей версии я сравниваю `ProductCode` по всем атрибутам, т.е. когда меняется хотя бы один атрибут (`code`, `discountCode`,  или `description` ), то это уже новый уникальный `ProductCode`. Поэтому код сейчас работает именно так, при изменении атрибута `code` делается новая запись в базу данных, т.к. объект считается новым. 
Если же требовалось сделать по-другому, например, не учитывать уникальность значения како-либо атрибута. Для этого нужно переписать метод `equals`.

2019-06-02 13:11 UTC, konivex requested changes
Исправьте замечания.

2019-06-02 13:11 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +    private ProductCode(ResultSet set) throws SQLException {
Этот конструктор инициализирует объект текущей записью из ResulSet'а.
Метод convert должен заполнять коллекцию продуктов, используя этот конструктор.

2019-06-02 13:11 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +            for (ProductCode productCode : collection) {
Зачем здесь цикл for?

2019-06-02 13:11 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +
Условие выбора обновляемой записи точно такое?

2019-06-03 08:19 UTC, AntonNeverovich commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +            for (ProductCode productCode : collection) {
В цикле происходит сравнение всех записей из базы данных с новой записью, которую нужно добавить в базу данных и если такая запись уже есть, то она обновляется, если ее нет, она добавляется как новая.

2019-06-03 08:24 UTC, AntonNeverovich commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +
Странно, у меня этот метод реализован. Без него программа бы не работала. Сейчас сделаю новый коммит и новый пул.
![8f11ce37-7b1b-4645-9057-38655ba26b0d](https://user-images.githubusercontent.com/47666059/58787251-186eb880-85f2-11e9-9cca-2d1c8a757055.jpg)

2019-06-03 08:48 UTC, AntonNeverovich commented on src/ru/avalon/java/j30/labs/ProductCode.java
> +    private ProductCode(ResultSet set) throws SQLException {
ОК.  Переписал.

2019-06-03 08:51 UTC, AntonNeverovich commented
Случайно удалил комментарий про метод `convert()`. Переписал метод ис использованием конструктора `private ProductCode(ResultSet set) throws SQLException`

2019-06-03 16:19 UTC, konivex approved these changes
Зачтено.

2019-07-23 18:26 UTC, closed without merging